package com.mycompany.carrental.entity;
// Generated 2017-06-05 18:33:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Future;


/**
 * Rents generated by hbm2java
 */
@Entity
@Table(name="rents"
    ,catalog="rental"
)
public class Rents  implements java.io.Serializable {


     private Integer idRents;
     private Users users;
     private Vehicles vehicles;
     private Date dateOfRental;
     private Date dateOfReturn;
     private float pricePerDay;

    public Rents() {
    }

    public Rents(Users users, Vehicles vehicles, Date dateOfRental, Date dateOfReturn, float pricePerDay) {
       this.users = users;
       this.vehicles = vehicles;
       this.dateOfRental = dateOfRental;
       this.dateOfReturn = dateOfReturn;
       this.pricePerDay = pricePerDay;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRents", unique=true, nullable=false)
    public Integer getIdRents() {
        return this.idRents;
    }
    
    public void setIdRents(Integer idRents) {
        this.idRents = idRents;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="users_idusers", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Vehicles_idVehicles", nullable=false)
    public Vehicles getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Vehicles vehicles) {
        this.vehicles = vehicles;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_of_rental", nullable=false, length=19)
    public Date getDateOfRental() {
        return this.dateOfRental;
    }
    
    public void setDateOfRental(Date dateOfRental) {
        this.dateOfRental = dateOfRental;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_of_return", nullable=false, length=19)
    public Date getDateOfReturn() {
        return this.dateOfReturn;
    }
    
    public void setDateOfReturn(Date dateOfReturn) {
        this.dateOfReturn = dateOfReturn;
    }

    
    @Column(name="price_per_day", nullable=false, precision=12, scale=0)
    public float getPricePerDay() {
        return this.pricePerDay;
    }
    
    public void setPricePerDay(float pricePerDay) {
        this.pricePerDay = pricePerDay;
    }




}


