package com.mycompany.carrental.entity;
// Generated 2017-06-05 18:33:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersRoles generated by hbm2java
 */
@Entity
@Table(name="users_roles"
    ,catalog="rental"
)
public class UsersRoles  implements java.io.Serializable {


     private Integer idUsersRoles;
     private Users users;
     private String name;

    public UsersRoles() {
    }

    public UsersRoles(Users users, String name) {
       this.users = users;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUsersRoles", unique=true, nullable=false)
    public Integer getIdUsersRoles() {
        return this.idUsersRoles;
    }
    
    public void setIdUsersRoles(Integer idUsersRoles) {
        this.idUsersRoles = idUsersRoles;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idusers")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


