package com.mycompany.carrental.entity;
// Generated 2017-06-05 18:33:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="rental"
    , uniqueConstraints = @UniqueConstraint(columnNames="nickname") 
)
public class Users  implements java.io.Serializable {


     private Integer idusers;
     private String name;
     private String surname;
     private String phone;
     private String email;
     private String password;
     private String company;
     private String nip;
     private String city;
     private String street;
     private String houseNumber;
     private String postalCode;
     private String nickname;
     private Set<Rents> rentses = new HashSet<Rents>(0);
     private Set<UsersRoles> usersRoleses = new HashSet<UsersRoles>(0);

    public Users() {
    }

	
    public Users(String name, String surname, String phone, String email, String password, String city, String street, String houseNumber) {
        this.name = name;
        this.surname = surname;
        this.phone = phone;
        this.email = email;
        this.password = password;
        this.city = city;
        this.street = street;
        this.houseNumber = houseNumber;
    }
    public Users(String name, String surname, String phone, String email, String password, String company, String nip, String city, String street, String houseNumber, String postalCode, String nickname, Set<Rents> rentses, Set<UsersRoles> usersRoleses) {
       this.name = name;
       this.surname = surname;
       this.phone = phone;
       this.email = email;
       this.password = password;
       this.company = company;
       this.nip = nip;
       this.city = city;
       this.street = street;
       this.houseNumber = houseNumber;
       this.postalCode = postalCode;
       this.nickname = nickname;
       this.rentses = rentses;
       this.usersRoleses = usersRoleses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idusers", unique=true, nullable=false)
    public Integer getIdusers() {
        return this.idusers;
    }
    
    public void setIdusers(Integer idusers) {
        this.idusers = idusers;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", nullable=false, length=45)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="phone", nullable=false, length=9)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="company", length=50)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="NIP", length=12)
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }

    
    @Column(name="city", nullable=false, length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="street", nullable=false, length=45)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="house_number", nullable=false, length=8)
    public String getHouseNumber() {
        return this.houseNumber;
    }
    
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    
    @Column(name="postal_code", length=5)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="nickname", unique=true, length=50)
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="users")
    public Set<Rents> getRentses() {
        return this.rentses;
    }
    
    public void setRentses(Set<Rents> rentses) {
        this.rentses = rentses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="users")
    public Set<UsersRoles> getUsersRoleses() {
        return this.usersRoleses;
    }
    
    public void setUsersRoleses(Set<UsersRoles> usersRoleses) {
        this.usersRoleses = usersRoleses;
    }




}


