package com.mycompany.carrental.entity;
// Generated 2017-06-05 18:33:45 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Vehicles generated by hbm2java
 */
@Entity
@Table(name = "vehicles", catalog = "rental"
)
public class Vehicles implements java.io.Serializable {

    private Integer idVehicles;
    @NotNull(message = "NaleĹĽy podaÄ‡ markÄ™")
    private Brands brands;
    @Size(min = 4, max = 40, message = "Niepoprawna dĹ‚ugoĹ›c nazwy modelu (min 4, max 40)")
    private String model;
    @NotNull(message = "NaleĹĽy podaÄ‡ datÄ™")
    private Date yearOfProduction;
    @Size(min = 4, max = 10, message = "Niepoprawna dĹ‚ugoĹ›Ä‡ nazwy typu paliwa (min 4. max 10)")
    private String fuelType;
    
    @Min(value = 0, message = "Zbyt maĹ‚a pojemnoĹ›c silnika")
    @Digits(integer = 12, fraction = 2, message = "Niepoprawna pojemnoĹ›Ä‡ silnika")
    @NotNull(message = "NaleĹĽy podaÄ‡ pojemnoĹ›Ä‡ silnika")
    private float engineCapacity;
    
    @Min(value = 0, message = "Niepoprawny przebieg auta")
    @Digits(integer = 10, fraction = 0, message = "Niepoprawny przebieg auta")
    @NotNull(message = "NaleĹĽy podaÄ‡ przebieg")
    private int carMileage;
    private String status;
    private List<Rents> rentses = new ArrayList<Rents>(0);

    public Vehicles() {
    }

    public Vehicles(Brands brands, String model, Date yearOfProduction, String fuelType, float engineCapacity, int carMileage, String status) {
        this.brands = brands;
        this.model = model;
        this.yearOfProduction = yearOfProduction;
        this.fuelType = fuelType;
        this.engineCapacity = engineCapacity;
        this.carMileage = carMileage;
        this.status = status;
    }

    public Vehicles(Brands brands, String model, Date yearOfProduction, String fuelType, float engineCapacity, int carMileage, List<Rents> rentses, String status) {
        this.brands = brands;
        this.model = model;
        this.yearOfProduction = yearOfProduction;
        this.fuelType = fuelType;
        this.engineCapacity = engineCapacity;
        this.carMileage = carMileage;
        this.rentses = rentses;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idVehicles", unique = true, nullable = false)
    public Integer getIdVehicles() {
        return this.idVehicles;
    }

    public void setIdVehicles(Integer idVehicles) {
        this.idVehicles = idVehicles;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idBrands", nullable = false)
    public Brands getBrands() {
        return this.brands;
    }

    public void setBrands(Brands brands) {
        this.brands = brands;
    }

    @Column(name = "model", nullable = false, length = 40)
    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "year_of_production", nullable = false, length = 10)
    public Date getYearOfProduction() {
        return this.yearOfProduction;
    }

    public void setYearOfProduction(Date yearOfProduction) {
        this.yearOfProduction = yearOfProduction;
    }

    @Column(name = "fuel_type", nullable = false, length = 10)
    public String getFuelType() {
        return this.fuelType;
    }

    public void setFuelType(String fuelType) {
        this.fuelType = fuelType;
    }

    @Column(name = "engine_capacity", nullable = false, precision = 12, scale = 0)
    public float getEngineCapacity() {
        return this.engineCapacity;
    }

    public void setEngineCapacity(float engineCapacity) {
        this.engineCapacity = engineCapacity;
    }

    @Column(name = "car_mileage", nullable = false)
    public int getCarMileage() {
        return this.carMileage;
    }

    public void setCarMileage(int carMileage) {
        this.carMileage = carMileage;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "vehicles")
    public List<Rents> getRentses() {
        return this.rentses;
    }

    public void setRentses(List<Rents> rentses) {
        this.rentses = rentses;
    }
    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
}
